name: ecommerce_app
description: Flutter eCommerce app (part of the Complete Flutter Course Bundle)

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.2.0
  google_fonts: 6.1.0 # ^6.2.0 require flutter version newer than 3.13.9