name: bfi_design_system_1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.2.0
  google_fonts: 6.1.0 # ^6.2.0 require flutter version newer than 3.13.9

dev_dependencies:
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  lint: ^2.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/