name: "units-test"
on:
  pull_request:

jobs:
  test:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: kefasjw/hello-world-javascript-action@main
      with:
        lcov-file: coverage/lcov.info
        comment-title: 'asdasd'
        all-files-minimum-coverage: 80
        changed-files-minimum-coverage: 90
        github-token: ${{ secrets.GITHUB_TOKEN }}