name: "units-test"
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    # permissions: write-all
    steps:
    - uses: actions/checkout@v3

    - name: Setup LCOV
      uses: hrishikesh-kadam/setup-lcov@v1

    - uses: kefasjw/lcov-pull-request-report@main
      with:
        lcov-file: coverage/lcov.info
        working-directory:
        comment-title: 'Todo App'
        all-files-minimum-coverage: 78
        changed-files-minimum-coverage: 70
        artifact-name: 'todo-app-coverage'
        github-token: ${{ secrets.GITHUB_TOKEN }}